name:                reddit-types
version:             0.1.0.0
github:              "githubuser/reddit-types"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - spec/fixtures/**/*.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/reddit-types#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - case-insensitive
  - data-diverse
  - fmt
  - megaparsec
  - http-types
  - servant
  - servant-client
  - text
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Wextra
  - -fno-warn-orphans

default-extensions:
  - BlockArguments
  - DataKinds
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - PatternSynonyms
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

library:
  source-dirs: src

tests:
  reddit-types-spec:
    main:                Spec.hs
    source-dirs:         spec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    build-tools:
      - hspec-discover
    dependencies:
      - reddit-types
      - hspec
      # - hspec-core
      - yaml
